version: '2'
volumes:
  user-terminal-log:
    external: true
    driver: rancher-nfs
  userhome:
    external: true
    driver: rancher-nfs
services:
  centos6-freeipa-sshd:
    image: claybbs/centos6-freeipa-client-sshd
    hostname: freeipa-client.freeipa.com
    environment:
      IPA_CLIENT_INSTALL_OPTS: --mkhomedir --force-join --domain=freeipa-server.freeipa.com  --server=freeipa-server.freeipa.com
      PASSWORD: root
    stdin_open: true
    volumes:
    - userhome:/home
    - user-terminal-log:/var/log/session
    tty: true
    ports:
    - 22:22/tcp
    labels:
      io.rancher.container.pull_image: always

